relaciones/muchos_a_muchos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='muchos_a_muchos_index'),
]

relaciones/muchos_a_uno/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='muchos_a_uno_index'),
]

relaciones/relaciones/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('muchos_a_uno/', include('muchos_a_uno.urls')),
    path('muchos_a_muchos/', include('muchos_a_muchos.urls')),
    path('uno_a_uno/', include('uno_a_uno.urls')),
]

relaciones/uno_a_uno/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('uno_a_uno', views.index, name='uno_a_uno_index'),
    
]

relaciones/muchos_a_muchos/models.py
from django.db import models

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    clientes = models.ManyToManyField(Cliente, through='Compra')

class Compra(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    fecha = models.DateField()

relaciones/muchos_a_uno/models.py
from django.db import models

class Region(models.Model):
    nombre = models.CharField(max_length=100)

class Estado(models.Model):
    nombre = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name="estados")

relaciones/uno_a_uno/models.py
from django.db import models

# Create your models here.
from django.db import models

class Trabajador(models.Model):
    nombre = models.CharField(max_length=100)

class Curriculum(models.Model):
    trabajador = models.OneToOneField(Trabajador, on_delete=models.CASCADE)
    documento = models.TextField()

relaciones/muchos_a_muchos/views.py
from django.shortcuts import render
from .models import Cliente

def index(request):
    context = {
        "clientes": Cliente.objects.all()
    }
    return render(request, 'muchos_a_muchos/index.html', context)

relaciones/muchos_a_uno/views.py
from django.shortcuts import render
from .models import Region

def index(request):
    context = {
        "regiones": Region.objects.all()
    }
    return render(request, 'muchos_a_uno/index.html', context)

relaciones/uno_a_uno/views.py
from django.shortcuts import render
from .models import Trabajador

def index(request):
    context = {
        "trabajadores": Trabajador.objects.all()
    }
    return render(request, 'uno_a_uno/index.html', context)

relaciones/muchos_a_muchos/templates/muchos_a_muchos/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Muchos a Muchos</title>
</head>

<body>
    <h1>Clientes y Productos (Muchos a Muchos)</h1>
    <ul>
        {% for cliente in clientes %}
        <li>{{ cliente.nombre }}
            <ul>
                {% for producto in cliente.producto_set.all %}
                <li>{{ producto.nombre }}</li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
</body>

</html>

relaciones/muchos_a_uno/templates/muchos_a_uno/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Muchos a Uno</title>
</head>

<body>
    <h1>Regiones y Estados (Muchos a Uno)</h1>
    <ul>
        {% for region in regiones %}
        <li>{{ region.nombre }}
            <ul>
                {% for estado in region.estados.all %}
                <li>{{ estado.nombre }}</li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
</body>

</html>

relaciones/uno_a_uno/templates/uno_a_uno/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Uno a Uno</title>
</head>

<body>
    <h1>Trabajadores y Curriculums (Uno a Uno)</h1>
    <ul>
        {% for trabajador in trabajadores %}
        <li>{{ trabajador.nombre }} - {{ trabajador.curriculum.documento }}</li>
        {% endfor %}
    </ul>
</body>

</html>